"""empty message

Revision ID: ca8f788a16c4
Revises: f7a241a11ca6
Create Date: 2022-02-17 12:04:09.671523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8f788a16c4'
down_revision = 'f7a241a11ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
